//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DLibTestWebApp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblkp_Lookup1
    {
        public int id { get; set; }
        public string value { get; set; }
        public string description { get; set; }
        public bool is_active { get; set; }
        public System.DateTime created_on { get; set; }
        public string created_by { get; set; }
        public System.DateTime modified_on { get; set; }
        public string modified_by { get; set; }
    }
}
